# Generated by Django 5.2.7 on 2025-10-27 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_anamnese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('recorrencia_valor', models.PositiveIntegerField(default=1)),
                ('recorrencia_unidade', models.CharField(choices=[('semanas', 'Semanas'), ('meses', 'Meses'), ('anos', 'Anos')], default='semanas', max_length=10)),
                ('recorrente', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(limit_choices_to={'tipo': 'profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_profissional', to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.vinculo')),
            ],
            options={
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
