# Generated by Django 5.2.7 on 2025-10-28 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0004_anamnese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('profissional', 'data', 'horario')},
        ),
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorrencia_valor', models.PositiveIntegerField(default=1)),
                ('recorrencia_unidade', models.CharField(choices=[('semanas', 'Semanas'), ('meses', 'Meses'), ('anos', 'Anos')], default='semanas', max_length=10)),
                ('horario_padrao', models.TimeField()),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana da consulta recorrente')),
                ('ativa', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias_paciente', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(limit_choices_to={'tipo': 'profissional'}, on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias_profissional', to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencia', to='pacientes.vinculo')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_geradas', to='consultas.recorrencia'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='recorrencia_unidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='recorrencia_valor',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='recorrente',
        ),
    ]
