# Generated by Django 5.2.7 on 2025-11-29 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_unique_together_recorrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_geradas', to='consultas.recorrencia'),
        ),
    ]
