# Generated by Django 5.2.7 on 2025-10-15 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_acontecimento', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.TextField()),
                ('pensamentos_automaticos', models.TextField()),
                ('emocao', models.TextField()),
                ('conclusao', models.TextField()),
                ('resultado', models.TextField()),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='rpds', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'profissional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpds_pacientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
