# Generated by Django 5.2.7 on 2025-10-16 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_humor', models.DateTimeField(default=django.utils.timezone.now)),
                ('emocao', models.CharField(choices=[('feliz', '😄 Feliz'), ('triste', '😢 Triste'), ('ansioso', '😰 Ansioso(a)'), ('tranquilo', '😌 Tranquilo(a)'), ('irritado', '😠 Irritado(a)'), ('desanimado', '😞 Desanimado(a)'), ('esperancoso', '😊 Esperançoso(a)')], max_length=20)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_humor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_humor'],
            },
        ),
    ]
