# Generated by Django 5.2.7 on 2025-10-21 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registrohumor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='anotacao_geral', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'profissional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes_gerais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
