# Generated by Django 5.2.7 on 2025-10-21 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_anotacaogeral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes_consulta_paciente', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'profissional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes_consulta_profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_consulta'],
            },
        ),
    ]
