# Generated by Django 5.2.7 on 2025-10-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_vinculo_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('vinculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.vinculo')),
            ],
        ),
    ]
