# Generated by Django 5.2.7 on 2025-10-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='crp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
